name: melon-bot-build
run-name: ${{ github.actor }} starts building the melon-bot
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Тут надо прописать тесты"
          # Тут надо тесты ебануть
  publis:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USERNAME }}
        #username: gitactions
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.KEY_PASSPHRASE }}
        port: 22
        script: |
          echo {$USER}
          ssh -T git@github.com
          cd ~/bot-base/melon-bot
          git pull git@github.com:SouryuuAsuka/melon-bot.git main
          git status
          cd ../bot-base-docker
          docker-compose build
          docker-compose up -d
